// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hblbwermqzsbibanrjpy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhibGJ3ZXJtcXpzYmliYW5yanB5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NjQyMDYsImV4cCI6MjA3MzU0MDIwNn0.B5CRABHZS_QOE-J5giqW2hlfDYN8UnXpPWicllZ7IeA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});